# Project-wide Gradle settings
org.gradle.jvmargs=-Xmx512m -XX:MaxMetaspaceSize=256m -Dfile.encoding=UTF-8 -XX:+UseG1GC
org.gradle.parallel=false
org.gradle.caching=true
org.gradle.configureondemand=true
org.gradle.daemon=false

# Kotlin
kotlin.code.style=official
kotlin.incremental=false
kotlin.daemon.jvmargs=-Xmx512m -XX:MaxMetaspaceSize=256m

# Android
android.useAndroidX=true
android.nonTransitiveRClass=true
android.nonFinalResIds=true
android.defaults.buildfeatures.compose=true
android.enableJetifier=false

# KSP
ksp.useKSP2=false

# Use less memory
org.gradle.workers.max=1
