package com.mahallu.manager.feature.members

import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.horizontalScroll
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.imePadding
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.rounded.Check
import androidx.compose.material3.DropdownMenu
import androidx.compose.material3.DropdownMenuItem
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.unit.dp
import androidx.hilt.navigation.compose.hiltViewModel
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import com.mahallu.manager.core.ui.components.AppButton
import feature.members.feature.members.R
import com.mahallu.manager.core.ui.components.AppTextField
import com.mahallu.manager.core.ui.components.ChipPill
import com.mahallu.manager.core.ui.components.TopAppBar
import com.mahallu.manager.core.ui.theme.LocalMahalluColors
import com.mahallu.manager.core.ui.util.Formatters

@Composable
fun MemberEditScreen(
    onDone: () -> Unit,
    viewModel: MemberEditViewModel = hiltViewModel()
) {
    val state by viewModel.state.collectAsStateWithLifecycle()
    val colors = LocalMahalluColors.current

    LaunchedEffect(state.saved) { if (state.saved) onDone() }

    Box(modifier = Modifier.fillMaxSize().background(colors.background)) {
        Column(modifier = Modifier.fillMaxSize()) {
            TopAppBar(
                title = if (state.id.isBlank()) stringResource(R.string.members_add_new) else stringResource(R.string.member_edit_edit_title),
                showBack = true,
                onBackClick = onDone,
                trailingActions = {
                    IconButton(onClick = { viewModel.save() }) {
                        Icon(Icons.Rounded.Check, contentDescription = stringResource(R.string.cd_save), tint = colors.primaryIndigo)
                    }
                }
            )

            Column(
                modifier = Modifier
                    .weight(1f)
                    .imePadding()
                    .verticalScroll(rememberScrollState())
                    .padding(horizontal = 16.dp, vertical = 12.dp)
            ) {
                AppTextField(
                    value = state.memberNumber,
                    onValueChange = { v -> viewModel.update { it.copy(memberNumber = v) } },
                    label = stringResource(R.string.member_field_member_id),
                    placeholder = stringResource(R.string.member_edit_autogenerated)
                )
                Spacer(Modifier.height(12.dp))
                Text(stringResource(R.string.member_field_family) + "*", style = MaterialTheme.typography.labelLarge, color = colors.textSecondary)
                Spacer(Modifier.height(6.dp))
                FamilyDropdown(
                    families = state.families,
                    selectedId = state.familyId,
                    onSelect = { id -> viewModel.update { it.copy(familyId = id) } }
                )

                Spacer(Modifier.height(12.dp))
                AppTextField(
                    value = state.name,
                    onValueChange = { v -> viewModel.update { it.copy(name = v) } },
                    label = stringResource(R.string.member_field_full_name),
                    placeholder = stringResource(R.string.member_edit_full_name_placeholder),
                    isRequired = true
                )
                Spacer(Modifier.height(12.dp))
                Text(stringResource(R.string.member_field_gender), style = MaterialTheme.typography.labelLarge, color = colors.textSecondary)
                Spacer(Modifier.height(6.dp))
                Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                    listOf("MALE", "FEMALE", "OTHER").forEach { g ->
                        ChipPill(text = g, selected = state.gender == g, onClick = { viewModel.update { it.copy(gender = g) } })
                    }
                }
                Spacer(Modifier.height(12.dp))
                AppTextField(
                    value = Formatters.date(state.dateOfBirth),
                    onValueChange = { },
                    label = stringResource(R.string.member_field_dob),
                    readOnly = true,
                    helperText = stringResource(R.string.member_edit_dob_helper)
                )
                Spacer(Modifier.height(12.dp))
                AppTextField(
                    value = state.mobile,
                    onValueChange = { v -> viewModel.update { it.copy(mobile = v) } },
                    label = stringResource(R.string.member_field_mobile),
                    keyboardType = KeyboardType.Phone
                )
                Spacer(Modifier.height(12.dp))
                AppTextField(
                    value = state.email,
                    onValueChange = { v -> viewModel.update { it.copy(email = v) } },
                    label = stringResource(R.string.member_field_email),
                    keyboardType = KeyboardType.Email
                )
                Spacer(Modifier.height(12.dp))
                AppTextField(
                    value = state.occupation,
                    onValueChange = { v -> viewModel.update { it.copy(occupation = v) } },
                    label = stringResource(R.string.member_field_occupation)
                )
                Spacer(Modifier.height(12.dp))
                AppTextField(
                    value = state.education,
                    onValueChange = { v -> viewModel.update { it.copy(education = v) } },
                    label = stringResource(R.string.member_field_education)
                )
                Spacer(Modifier.height(12.dp))
                AppTextField(
                    value = state.bloodGroup,
                    onValueChange = { v -> viewModel.update { it.copy(bloodGroup = v) } },
                    label = stringResource(R.string.member_field_blood_group)
                )
                Spacer(Modifier.height(12.dp))
                Text(stringResource(R.string.member_field_marital_status), style = MaterialTheme.typography.labelLarge, color = colors.textSecondary)
                Spacer(Modifier.height(6.dp))
                Row(
                    modifier = Modifier.horizontalScroll(rememberScrollState()),
                    horizontalArrangement = Arrangement.spacedBy(8.dp)
                ) {
                    listOf("SINGLE", "MARRIED", "DIVORCED", "WIDOWED").forEach { s ->
                        ChipPill(text = s, selected = state.maritalStatus == s, onClick = { viewModel.update { it.copy(maritalStatus = s) } })
                    }
                }
                Spacer(Modifier.height(12.dp))
                AppTextField(
                    value = state.relationToHead,
                    onValueChange = { v -> viewModel.update { it.copy(relationToHead = v) } },
                    label = stringResource(R.string.member_field_relation)
                )
                Spacer(Modifier.height(12.dp))
                AppTextField(
                    value = state.address,
                    onValueChange = { v -> viewModel.update { it.copy(address = v) } },
                    label = stringResource(R.string.member_field_address),
                    maxLines = 3,
                    singleLine = false
                )
                Spacer(Modifier.height(12.dp))
                AppTextField(
                    value = state.emergencyContactName,
                    onValueChange = { v -> viewModel.update { it.copy(emergencyContactName = v) } },
                    label = stringResource(R.string.member_field_emergency_name)
                )
                Spacer(Modifier.height(12.dp))
                AppTextField(
                    value = state.emergencyContactNumber,
                    onValueChange = { v -> viewModel.update { it.copy(emergencyContactNumber = v) } },
                    label = stringResource(R.string.member_field_emergency_number),
                    keyboardType = KeyboardType.Phone
                )
                Spacer(Modifier.height(12.dp))
                AppTextField(
                    value = state.notes,
                    onValueChange = { v -> viewModel.update { it.copy(notes = v) } },
                    label = stringResource(R.string.member_field_notes),
                    maxLines = 3,
                    singleLine = false
                )
                if (!state.error.isNullOrBlank()) {
                    Spacer(Modifier.height(8.dp))
                    Text(state.error ?: "", color = colors.error, style = MaterialTheme.typography.bodySmall)
                }
                Spacer(Modifier.height(20.dp))
                AppButton(
                    text = if (state.isSaving) stringResource(R.string.member_saving) else stringResource(R.string.member_save),
                    onClick = { viewModel.save() },
                    isLoading = state.isSaving
                )
                Spacer(Modifier.height(24.dp))
            }
        }
    }
}

@Composable
private fun FamilyDropdown(
    families: List<com.mahallu.manager.core.database.entity.FamilyEntity>,
    selectedId: String,
    onSelect: (String) -> Unit
) {
    val colors = LocalMahalluColors.current
    var expanded by remember { mutableStateOf(false) }
    val selected = families.firstOrNull { it.id == selectedId }
    val display = selected?.let { stringResource(R.string.member_family_selector, it.familyNumber, it.houseName) } ?: stringResource(R.string.member_edit_select_family)
    Box(modifier = Modifier.fillMaxWidth()) {
        Box(
            modifier = Modifier
                .fillMaxWidth()
                .height(48.dp)
                .clip(RoundedCornerShape(10.dp))
                .background(colors.surfaceVariant)
                .clickable { expanded = true }
                .padding(horizontal = 14.dp),
            contentAlignment = Alignment.CenterStart
        ) {
            Text(
                text = display,
                color = if (selected != null) colors.textPrimary else colors.textTertiary,
                style = MaterialTheme.typography.bodyMedium
            )
        }
        DropdownMenu(expanded = expanded, onDismissRequest = { expanded = false }) {
            families.forEach { f ->
                DropdownMenuItem(
                    text = { Text(stringResource(R.string.member_family_selector, f.familyNumber, f.houseName)) },
                    onClick = {
                        onSelect(f.id)
                        expanded = false
                    }
                )
            }
        }
    }
}